on:
  # Triggers the workflow on push events
  push:
    branches: [ "main" ]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Hello World
        run: echo "Hello World!"