on:
  # Triggers the workflow on push events
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: self-hosted
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Hello World
        run: echo "Hello World!"
